### ISSUE TITLE
Duplicate Triggers for each player

### ISSUE THREAD

**Issue by LoboFJP** [KSneijders/AoE2ScenarioParser#10]
Hi, I'm new here and I would like to know what is the correct syntax to duplicate a trigger for each player:

```
from AoE2ScenarioParser.scenarios.aoe2_de_scenario import AoE2DEScenario
from AoE2ScenarioParser.datasets.players import PlayerId

input_path = r"C:\Users\xaero\Games\Age of Empires 2 DE\76561198062020840\resources\_common\scenario\CB_King_Edition_Doge.aoe2scenario"
output_path = r"C:\Users\xaero\Desktop\Escenarios AOE2"
scenario = AoE2DEScenario.from_file(input_path)

trigger_manager = scenario.trigger_manager

copied_triggers = trigger_manager.copy_trigger_per_player(
    from_player=PlayerId.ONE,
    trigger_select=TS.index(610),
    create_copy_for_players=[
        PlayerId.TWO, PlayerId.THREE, PlayerId.FOUR, PlayerId.FIVE, PlayerId.SIX, PlayerId.SEVEN, PlayerId.EIGHT 
    ]
)

scenario.write_to_file(output_path)

```
But I get this error
![imagen](https://user-images.githubusercontent.com/26876102/113494803-279e4600-94a9-11eb-9538-4ab0dec6d079.png)

This is the trigger that I want to duplicate

![imagen](https://user-images.githubusercontent.com/26876102/113494812-3e449d00-94a9-11eb-92d8-7e86704a1f2c.png)

I know this is a noob mistake, but I would like to know how to correct it.

Thanks

**Comment by KSneijders** [comment]
Hey, thanks for creating the issue. The exact reason for your error is because you didn't import `TS`. I see that in the docs it doesn't state where to import it from, so I'll add that soon. You can find the docs here btw:

https://aoe2scenarioparser.readthedocs.io/en/master/examples/triggers.html#select-existing-triggers

The import you need looks like this:

    from AoE2ScenarioParser.objects.support.trigger_select import TS

Also, if you want to copy a trigger for each player except for the `from_player` you can leave the `create_copy_for_players` list empty. It defaults to all players but the one you give as source.

Hope this helps 😄

**Comment by LoboFJP** [comment]
Hello again i tried this:

```
from AoE2ScenarioParser.scenarios.aoe2_de_scenario import AoE2DEScenario
from AoE2ScenarioParser.datasets.players import PlayerId
from AoE2ScenarioParser.objects.support.trigger_select import TS

input_path = r"C:\Users\xaero\Games\Age of Empires 2 DE\76561198062020840\resources\_common\scenario\CB_King_Edition_Doge.aoe2scenario"
output_path = r"C:\Users\xaero\Desktop\Escenarios AOE2\CB_King_Edition_Doge.aoe2scenario"
scenario = AoE2DEScenario.from_file(input_path)

trigger_manager = scenario.trigger_manager

copied_triggers = trigger_manager.copy_trigger_per_player(
    from_player=PlayerId.ONE,
    trigger_select=TS.index(638),
    create_copy_for_players=[
        PlayerId.TWO, PlayerId.THREE, PlayerId.FOUR, PlayerId.FIVE, PlayerId.SIX, PlayerId.SEVEN, PlayerId.EIGHT 
    ]
)

scenario.write_to_file(output_path)
```
But I get this error

![imagen](https://user-images.githubusercontent.com/26876102/113522974-7fe94c80-956a-11eb-88b1-5a807483376c.png)

Then i tried this:

```
from AoE2ScenarioParser.scenarios.aoe2_de_scenario import AoE2DEScenario
from AoE2ScenarioParser.datasets.players import PlayerId
from AoE2ScenarioParser.objects.support.trigger_select import TS

input_path = r"C:\Users\xaero\Games\Age of Empires 2 DE\76561198062020840\resources\_common\scenario\CB_King_Edition_Doge.aoe2scenario"
output_path = r"C:\Users\xaero\Desktop\Escenarios AOE2\CB_King_Edition_Doge2.aoe2scenario"
scenario = AoE2DEScenario.from_file(input_path)

trigger_manager = scenario.trigger_manager

copied_triggers = trigger_manager.copy_trigger_per_player(
    from_player=PlayerId.ONE,
    trigger_select=TS.index(637),
    create_copy_for_players=[]
)

scenario.write_to_file(output_path)
```
It did not give me any error but neither did duplicate any trigger

**Comment by KSneijders** [comment]
Thanks for letting me know. I'm currently on my phone as it's 1:30 am but that looks like a bug within the parser. So for that. Will take a look at it tomorrow. If it's a bug I'll try and push a fix for it the same day. I'll keep you updated here!

**Comment by KSneijders** [comment]
I just published a new version (`0.1.7`). Which fixes the recursion error issue. 
Thanks again for the report, and let me know if you find find any other issues!

**Comment by LoboFJP** [comment]
Thanks, it works :D

**Comment by KSneijders** [comment]
> It did not give me any error but neither did duplicate any trigger

I just noticed I said it wrong, I said: "_you can leave the create_copy_for_players list empty_". I meant, just leave out the entire argument. Like so:
```py
copied_triggers = trigger_manager.copy_trigger_per_player(
    from_player=PlayerId.ONE,
    trigger_select=TS.index(637)
)
```

**Comment by LoboFJP** [comment]
Oh, thanks again. Question, is there a way to copy just the effects of 1 trigger and put in the same trigger?

**Comment by KSneijders** [comment]
I think it'd be easier to communicate using discord as this is not relevant to the mentioned issue, please send me a message: 
MrKirby#5063
