### ISSUE TITLE
Documentation outdated?

### ISSUE THREAD

**Issue by botist** [KSneijders/AoE2ScenarioParser#12]
using ``from AoE2ScenarioParser.datasets.units import UnitId`` gives me an import error, and ``TS`` is undefined

**Comment by KSneijders** [comment]
Could you provide some context and code which reproduces the error?
And what version of the parser are you using?

**Comment by KSneijders** [comment]
I see now where the mistake happened. The docs for datasets was updated. You can find all info about how the unit datasets work there. I forgot to update the unit dataset docs. I'll update those as soon as I can!

**Comment by KSneijders** [comment]
I just released version `0.1.8` which, among other things, fixed the documentation issue

**Comment by botist** [comment]
It works fine now, thank you!

**Comment by botist** [comment]
Thank you for the documentation update!
