### ISSUE TITLE
How can I export triggers from one scenario to another?

### ISSUE THREAD

**Issue by ElGoncen** [KSneijders/AoE2ScenarioParser#14]
I am not a programmer, however I have managed to understand some of the logic of this code

I have tried to export the triggers from one scenario to others already created.

first I run the commands:

```
from AoE2ScenarioParser.scenarios.aoe2_de_scenario import AoE2DEScenario

input_path =  "D:/Documents/My Games/Age of Empires 2/escenario1/1.aoe2scenario"
output_path = "D:/Documents/My Games/Age of Empires 2/escenario2/2.aoe2scenario"

scenario = AoE2DEScenario.from_file(input_path)
trigger_manager = scenario.trigger_manager

```

then to the scribe in the secondary stage I put this:

`scenario.write_to_file(output_path)`

and it only makes a copy of all the elements (units, terrains, players, triggers etc)

I have tried testing with these commands.

```
from AoE2ScenarioParser.objects.support.trigger_select import TS

input_path =  "D:/Documents/My Games/Age of Empires 2/escenario1/1.aoe2scenario"
output_path = "D:/Documents/My Games/Age of Empires 2/escenario2/2.aoe2scenario"
```
trying to only load triggers and not all resources
but I get an error

```
[Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'TriggerSelect' has no attribute 'from_file'](url)
```

Obviously that's not the case, but as I said, I am not a pytrhon programmer but I already tried everything that occurred to me and I have not been successful

could you help me?

**Comment by KSneijders** [comment]
Hey! 
Just so I understand, you're trying to copy triggers from one scenario and basically paste them on top of an existing scenario? Right?
If so, are there triggers in the other scenarios and if so, do you want to keep them?

A simple example which will override all triggers in the other scenarios is:

```py
from AoE2ScenarioParser.scenarios.aoe2_de_scenario import AoE2DEScenario

trigger_scenario = AoE2DEScenario.from_file("PATH_TO_FILE_WITH_TRIGGERS.aoe2scenario")
other_scenario = AoE2DEScenario.from_file("PATH_TO_SCENARIO_TO_PASTE_TRIGGERS.aoe2scenario")

other_scenario.trigger_manager.triggers = trigger_scenario.trigger_manager.triggers

other_scenario.write_to_file("OUTPUT_PATH.aoe2scenario")
```

Hope that helps :)
Let me know if you have any other questions

**Comment by ElGoncen** [comment]
If that's what I'm looking for, thank you very much. But is there a way that the existing triggers in the other scenario would not be deleted or invalidated?

Excuse my English, I use a translator

**Comment by KSneijders** [comment]
Your English is fine, don't worry. Yeah the existing triggers can also be kept!

Just replace the `=` with a `+=` like below
```py
other_scenario.trigger_manager.triggers += trigger_scenario.trigger_manager.triggers
```

**Comment by ElGoncen** [comment]
Amazing, it worked! Thank you very much, it saved me a lot of work time, you are geniuses.
Would there be a problem if I share this information as a tutorial in my language on my blogs and sites like steam?

**Comment by KSneijders** [comment]
Glad it worked!
And of course not! Share it as much as you want 😄 - a link to the github page would of course be appreciated but nothing is mandatory.
I'll close this issue for now. If you have any other questions, feel free to create a new issue 🙂
