### ISSUE TITLE
Scenario Crash After duplicate triggers

### ISSUE THREAD

**Issue by LoboFJP** [KSneijders/AoE2ScenarioParser#21]
Hello.
This time it is an error that occurs after duplicating triggers.
In VS it gives me this message:
**File writing finished successfully.
File successfully written to: 'C:\Users\xaero\Games\Age of Empires 2 DE\76561198062020840\resources\_common\scenario\CBA DoGo Edition.aoe2scenario'**

Also in the game apparently everything is fine

![imagen](https://user-images.githubusercontent.com/26876102/124848935-71dd0a80-df63-11eb-9f40-0a1c684eb66d.png)

But when I open the map

![imagen](https://user-images.githubusercontent.com/26876102/124848981-85887100-df63-11eb-9bd3-e97ccc8259c5.png)

I have backup of the map and I was able to recover it, but when retrying duplicate trigger the same error occurred

The Code:

```
from AoE2ScenarioParser.scenarios.aoe2_de_scenario import AoE2DEScenario
from AoE2ScenarioParser.datasets.players import PlayerId
from AoE2ScenarioParser.objects.support.trigger_select import TS

input_path = r"C:\Users\xaero\Games\Age of Empires 2 DE\76561198062020840\resources\_common\scenario\CBA DoGo Edition.aoe2scenario"
output_path = r"C:\Users\xaero\Games\Age of Empires 2 DE\76561198062020840\resources\_common\scenario\CBA DoGo Edition.aoe2scenario"
scenario = AoE2DEScenario.from_file(input_path)

trigger_manager = scenario.trigger_manager
copied_triggers = trigger_manager.copy_trigger_per_player(
    from_player=PlayerId.ONE,
    trigger_select=TS.index(2832),
    create_copy_for_players=[
        PlayerId.TWO, PlayerId.THREE, PlayerId.FOUR, PlayerId.FIVE, PlayerId.SIX, PlayerId.SEVEN, PlayerId.EIGHT
    ]
)

scenario.write_to_file(output_path)

```
Edith1: Only 1 duplicate trigger appears in the code, but there were approximately 80 duplicates for 8 players
Edith2: I tested again duplicating just 1 trigger, but got the same error T_T

**Comment by KSneijders** [comment]
Hey, thanks for the report. 

I've published the version `0.1.11` which fixes the issue. Sorry for the inconvenience!
The error was caused by a single value being different by default. I didn't have time to thoroughly test the update last night, so thanks again for the report!
