### ISSUE TITLE
loading in standard maps (potential build order testing/optimization)

### ISSUE THREAD

**Issue by bgriffen** [KSneijders/AoE2ScenarioParser#32]
Nice work. Just wondering if this can be used to generate a map or a "scenario" of say Arabia in a 1v1, 2v2 setting. Having all of the coordinates of resources would be a backhanded way of developing a build order optimizer using a few basic hand coded constants (such as traversal distance, mining rates etc). Is thee any way to load in the standard map layouts? 

Ty

**Comment by KSneijders** [comment]
Aah, no, you cannot read a replay file. This package reads scenario files (hence the name AoE2ScenarioParser) 🙂.

If you want to read replay files you can use the site: https://aoe2recs.com/ although that's for multiplayer games I think. I'd recommend asking this question in the SE (Siege Engineers) discord, in the rec-analyses channel. 

SE Discord: https://discordapp.com/invite/njAsNuD

I saw you also had a talk with someone in the discord, so we can continue questions there if you have any 🙂
