### ISSUE TITLE
Can't even get the example to work

### ISSUE THREAD

**Issue by Lownek** [KSneijders/AoE2ScenarioParser#33]
Excuse me, maybe it is my low skills on python but I can't really get the script to work. I tried the most basic of the examples in the documentation (loading a file) but no matter what I do I still get this error message:

> Traceback (most recent call last):
  File "C:\Users\SantiPC\Desktop\AoE2ScenarioParser-0.1.28\trigger check.py", line 30, in <module>
    from AoE2ScenarioParser.scenarios.aoe2_de_scenario import AoE2DEScenario
  File "C:\Users\SantiPC\Desktop\AoE2ScenarioParser-0.1.28\AoE2ScenarioParser\scenarios\aoe2_de_scenario.py", line 4, in <module>
    from AoE2ScenarioParser.objects.managers.de.trigger_manager_de import TriggerManagerDE
  File "C:\Users\SantiPC\Desktop\AoE2ScenarioParser-0.1.28\AoE2ScenarioParser\objects\managers\de\trigger_manager_de.py", line 4, in <module>
    from AoE2ScenarioParser.objects.data_objects.trigger import Trigger
  File "C:\Users\SantiPC\Desktop\AoE2ScenarioParser-0.1.28\AoE2ScenarioParser\objects\data_objects\trigger.py", line 16, in <module>
    from AoE2ScenarioParser.objects.support.uuid_list import UuidList
  File "C:\Users\SantiPC\Desktop\AoE2ScenarioParser-0.1.28\AoE2ScenarioParser\objects\support\uuid_list.py", line 3, in <module>
    from typing_extensions import SupportsIndex
ModuleNotFoundError: No module named 'typing_extensions'
>>> 

I have used this in the past and now that I need it again I had to update it. I did the pip install and everything, I'm 99% sure I've setup everything right but still I always get that message.

**Comment by KSneijders** [comment]
Hi, this is something that was fixed in the latest version (0.1.28). What command did you use to update the parser?

**Comment by Lownek** [comment]
I downloaded the new version, then I used pip install AoE2ScenarioParser and then I used pip install --upgrade AoE2ScenarioParser.

**Comment by KSneijders** [comment]
The package in your error should be automatically installed when you use pip. You can install it manually using `pip install <name>` as well, but shouldn't be necessary

**Comment by Lownek** [comment]
Thanks for you attention. As I said, I'm not good at python and I'm sure it must have been me who did something wrong. Nevertheless, I have installed typing_extensions manually and the error has now changed. When trying to read a file, some of the feedback seems to have wrong ascii characters. Here's the error message:

> 
[35m
Reading file: 'C:\Users\SantiPC\Desktop\AoE2ScenarioParser-0.1.28\input\Warriors RPG v1,03.aoe2scenario'[0m

Reading scenario file...
Reading scenario file finished successfully.

[34m
############### Attributes ###############[0m

[34m>>> Game version: 'DE'[0m

[34m>>> Scenario version: 1.45[0m

[34m##########################################[0m


Loading scenario structure...Traceback (most recent call last):
  File "C:\Users\SantiPC\Desktop\AoE2ScenarioParser-0.1.28\AoE2ScenarioParser\scenarios\aoe2_scenario.py", line 284, in get_version_dependant_structure_file
    with (vdir / game_version / f'v{scenario_version}' / f'{name}.json').open() as structure_file:
  File "C:\Users\SantiPC\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Users\SantiPC\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\SantiPC\\Desktop\\AoE2ScenarioParser-0.1.28\\AoE2ScenarioParser\\versions\\DE\\v1.45\\conditions.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SantiPC\Desktop\AoE2ScenarioParser-0.1.28\trigger check.py", line 36, in <module>
    scenario = AoE2DEScenario.from_file(input_folder + "Warriors RPG v1,03.aoe2scenario")
  File "C:\Users\SantiPC\Desktop\AoE2ScenarioParser-0.1.28\AoE2ScenarioParser\scenarios\aoe2_de_scenario.py", line 34, in from_file
    return super().from_file(filename, game_version)
  File "C:\Users\SantiPC\Desktop\AoE2ScenarioParser-0.1.28\AoE2ScenarioParser\scenarios\aoe2_scenario.py", line 81, in from_file
    initialise_version_dependencies(scenario.game_version, scenario.scenario_version)
  File "C:\Users\SantiPC\Desktop\AoE2ScenarioParser-0.1.28\AoE2ScenarioParser\scenarios\aoe2_scenario.py", line 225, in initialise_version_dependencies
    condition_json = get_version_dependant_structure_file(game_version, scenario_version, "conditions")
  File "C:\Users\SantiPC\Desktop\AoE2ScenarioParser-0.1.28\AoE2ScenarioParser\scenarios\aoe2_scenario.py", line 288, in get_version_dependant_structure_file
    raise UnknownStructureError(f"The structure {name} could not be found with: {v}")
AoE2ScenarioParser.helper.exceptions.UnknownStructureError: The structure conditions could not be found with: DE:1.45


Remember, it's just the most basic "read file" example from the documentation what I'm trying to run, just 3 lines of code. I tried to sort the mistake out here but again, my skills reading this are limited and I'm surely the one who made the mistake.
Thanks in advance.

**Comment by KSneijders** [comment]
I'm not entirely sure what's going on with your parser installation but something seems to have messed up quite clearly. Can you check the version you're on? And maybe try and reinstall the parser completely:

`pip install --force-reinstall AoE2ScenarioParser==0.1.28`

**Comment by Lownek** [comment]
I forced reinstall and I even made a new fresh installation in another drive, I also tried loading older scenarios from different older versions of DE and I always got the same error message. Then I had an idea: Updating my 3.9.2 python version (though it should be able to run the parser nonetheless) to 3.10. Doing this brought me back to the same typing_extensions error. So I tried installing it again through pip but it told me I already had it. I'm confused now, running with 3.9.2 gives me an error, 3.10 gives me another.

**Comment by KSneijders** [comment]
This all sounds a lot like you're using a venv (Virtual Environment) which is a separate pip installation for a specific project (It's a default checked checkbox when creating a project using PyCharm for example)

Try executing the above commands in the folder of your project (there also might be a `venv` folder)
Maybe try and create a new project and make sure to not create a venv. You can do `pip show` in the new folder and if you see the parser without doing anything else it means you're using the global pip

**Comment by Lownek** [comment]
I used AoE2SP back when it was on version 0.1.7 (april 2021) and I never had trouble with any virtual environment. Anyway, I used `pip show` on my project directory, it asked me to specify a package and when I put AoE2ScenarioParser it just gave me the info in the setup.py. As for pycharm, I have no clue on how to start a project without the `venv`. Could you tell me how to avoid creating a virtual environment? Or better yet, how to install the AoE2ScenarioParser and typing_extensions on the `venv`. I guess this last option could work.

**Comment by KSneijders** [comment]
Awesome! And yeah, venvs are one of the common pitfalls when using python. Had a lot of issues with it as well when I started 😄

---

And indeed you're right, installing the packages inside the venv is better than global. Mainly because you could leave the project as is and come back to it in a year. If the parser syntax changed and you kept using the parser from the global installation you'd have updated it and your older projects wouldn't run at all anymore. With a venv this is not an issue as it retains this project version (until you update this specific installation ofc)

**Comment by Lownek** [comment]
(I was editing this on the previous comment when you answered so i'm doing this on a new one).
Well never mind the previous thing, It actually didn't work that time because the error wasn't showing but was still present. Anyway, I got around it to work. Aparently if I go to the module downloaded by pip and copy the folder "AoE2ScenarioParser" content and paste those in the main download file it works perfectly. It may sound reasonable to you because you programmed it but for me it was just out of pure desperation. Issue Closed and out.

**Comment by KSneijders** [comment]
Sorry to hear it's not working... But that doesn't sound reasonable at all... You should just be able to execute the pip command and done, it works... Maybe join the discord server and open a thread in the #questions channel if you want me (or others) to look into it.

It's probably some config which isn't set properly or it's the python/pip installation... It's hard to tell at the moment.

Glad you got it to work right now but I'd advice you to properly try and fix it some time because updating probably won't work at the moment.
