### ISSUE TITLE
bidict dependency is missing in PyPI

### ISSUE THREAD

**Issue by lobotrock** [KSneijders/AoE2ScenarioParser#7]
After running 
```bash
 pip install AoE2ScenarioParser==0.0.17
```
Then running the following in Python 3.8
```python
from AoE2ScenarioParser.aoe2_scenario import AoE2Scenario
```
Will result in the error:
```
ModuleNotFoundError: No module named 'bidict'
```

A temporary fix is running `pip install bidict` but a long term solution would be to include `bidict` as a dependency for `AoE2Scenario`

**Comment by KSneijders** [comment]
Thanks for letting me know! I've now added it to the dependencies! (I thought it was already in there)
I just released version 0.0.18. When installing this version bidict is automatically installed with it.

```
>>> pip install AoE2ScenarioParser
Collecting AoE2ScenarioParser
  Downloading AoE2ScenarioParser-0.0.18-py3-none-any.whl (117 kB)
     |████████████████████████████████| 117 kB 6.8 MB/s
Collecting bidict>=0.21.2
  Using cached bidict-0.21.2-py2.py3-none-any.whl (37 kB)
Installing collected packages: bidict, AoE2ScenarioParser
Successfully installed AoE2ScenarioParser-0.0.18 bidict-0.21.2
```
