### ISSUE TITLE
[Help] Get access to DataHeaderPiece in a legal way

### ISSUE THREAD

**Issue by OhtAzi** [KSneijders/AoE2ScenarioParser#8]
Hi,

**Description:**
Recently I am writing a small tool to help me re-index all the units and re-set next_unit_id_to_place.
![1](https://user-images.githubusercontent.com/79516996/109393518-91d14180-7965-11eb-8aa1-4abb91279674.png)
The code looks like this:
```
units = scenario.unit_manager.get_all_units()
index = 0
for unit in units:
    if unit.reference_id >= 0:
        unit.reference_id = index
        index = index + 1
data._parsed_data["DataHeaderPiece"].next_unit_id_to_place = index
```
**Question:**
Would you mind telling me whether there is a legal way to modify the DataHeader without getting access to a private variable?

**Comment by KSneijders** [comment]
Hey! Currently there's no way to access this variable a 'legal' way. This indeed is how I'd do it currently when using the parser.
There's a lot of values in a scenario (as you clearly know) and I intend for them to eventually all be accessible in a proper way but it'll take quite some time. My current focus is on a branch which deals **a lot** better with versions.   
So for now, unfortunately no there is not, sorry 😕

**Comment by OhtAzi** [comment]
> Hey! Currently there's no way to access this variable a 'legal' way. This indeed is how I'd do it currently when using the parser.
> There's a lot of values in a scenario (as you clearly know) and I intend for them to eventually all be accessible in a proper way but it'll take quite some time. My current focus is on a branch which deals **a lot** better with versions.
> So for now, unfortunately no there is not, sorry 😕

Thank you so much for the prompt reply and explanation.
Anyway, currently, I do have the ability to get access to all those variables. That is enough.

I like this project and really appreciate your effort.👍
