### ISSUE TITLE
Variable Names

### ISSUE THREAD

**Issue by Lownek** [KSneijders/AoE2ScenarioParser#9]
Hello, I'm currently using AoE2ScenarioParser-0.1.5 and when I load a scenario and print all triggers with print(trigger_manager.get_summary_as_string()) all used variables seem to be named "VariableStruct". If I write the file and open it on AoE2DE I see the variable names were indeed changed to VariableStruct and if I try to change their name there is a high chance of crashing my game. I don't know if it is related to some recent update of AoE2DE. Anyway, I'd also like to thank you for this -very- useful tool.

**Comment by KSneijders** [comment]
Thanks for the report! 
You're right, it's an issue with the parser introduced in `0.1.0`. I have a fix ready and will hopefully push it before the end of the day (couple hours)
